# Generated by Django 5.1.2 on 2024-10-20 00:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kategoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Produkt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=200)),
                ('cena', models.DecimalField(decimal_places=2, max_digits=10)),
                ('opis', models.TextField()),
                ('sadzonka_image', models.ImageField(upload_to='images/')),
                ('mlode_drzewo_image', models.ImageField(upload_to='images/')),
                ('dorosle_drzewo_image', models.ImageField(upload_to='images/')),
                ('kategoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produkty.kategoria')),
                ('tagi', models.ManyToManyField(to='produkty.tag')),
            ],
        ),
        migrations.CreateModel(
            name='Dostawa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typ', models.CharField(choices=[('mała', 'Mała'), ('duża', 'Duża')], max_length=100)),
                ('koszt', models.DecimalField(decimal_places=2, max_digits=5)),
                ('produkt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produkty.produkt')),
            ],
        ),
    ]
